# Generated by Django 3.0.3 on 2020-07-06 03:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('emoji', models.CharField(max_length=32)),
                ('gender', models.CharField(max_length=8)),
                ('beauty', models.DecimalField(decimal_places=2, max_digits=4)),
                ('glassPoss', models.IntegerField()),
                ('glaType', models.CharField(max_length=32)),
                ('dateTime', models.DateTimeField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
