# Generated by Django 3.0.3 on 2020-07-06 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='glassPoss',
            new_name='glaPoss',
        ),
    ]
