# Generated by Django 3.0.3 on 2020-07-07 20:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0003_user'),
    ]
    
    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='username',
            new_name='user',
        ),
    ]
