# Generated by Django 3.0.3 on 2020-07-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200707_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='glaPoss',
            field=models.FloatField(),
        ),
    ]
